name: Build and Upload Debug Android App

on:
  push:
    branches:
      - develop

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build the app
        run: ./gradlew assembleDebug
      - name: Upload apk
        uses: actions/upload-artifact@v3
        with:
          name: debug apk
          path: app/build/outputs/apk/debug/app-debug.apk