name: Upload retrace mapping file

on:
  push:
    branches:
      - main

jobs:
  create-and-upload-mapping:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build the app
        run: ./gradlew assembleRelease
      - name: Upload mapping
        uses: actions/upload-artifact@v3
        with:
          name: mapping
          path: app/build/outputs/mapping/release/mapping.txt